// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  testimonials: dynamic(() => import("./Testimonials")),
};
